In [1]:
import pandas as pd
# Oringinal Data (RAW) "MTA_Subway_Hourly_Ridership__2020-2024_20260222.csv"
daily_ridership = pd.read_csv("MTA_Subway_Daily_Manhattan.csv")
st_cmplx_list = pd.read_csv("MTA_Subway_Daily_Manhattan_Stations.csv")

In [2]:
daily_ridership

       station_complex_id        date  ridership
0                       8  2023-01-01       8909
1                       8  2023-01-02       7475
2                       8  2023-01-03       9291
3                       8  2023-01-04      10697
4                       8  2023-01-05      10391
...                   ...         ...        ...
44128                 635  2023-12-27      18878
44129                 635  2023-12-28      20035
44130                 635  2023-12-29      23840
44131                 635  2023-12-30      15912
44132                 635  2023-12-31      11406

[44133 rows x 3 columns]

In [3]:
daily_ridership_totals = daily_ridership.groupby('date')['ridership'].sum().reset_index()

In [4]:
daily_ridership_totals

           date  ridership
0    2023-01-01    1013185
1    2023-01-02    1062726
2    2023-01-03    1734883
3    2023-01-04    1862526
4    2023-01-05    1865376
..          ...        ...
360  2023-12-27    1668616
361  2023-12-28    1769432
362  2023-12-29    1846550
363  2023-12-30    1469037
364  2023-12-31    1128420

[365 rows x 2 columns]

In [5]:
daily_ridership_totals.to_csv("MTA_Subway_Daily_Manhattan_Totals.csv", index=False)

In [6]:
export_check = pd.read_csv("MTA_Subway_Daily_Manhattan_Totals.csv")
export_check

           date  ridership
0    2023-01-01    1013185
1    2023-01-02    1062726
2    2023-01-03    1734883
3    2023-01-04    1862526
4    2023-01-05    1865376
..          ...        ...
360  2023-12-27    1668616
361  2023-12-28    1769432
362  2023-12-29    1846550
363  2023-12-30    1469037
364  2023-12-31    1128420

[365 rows x 2 columns]

In [7]:
#daily_ridership_totals = pd.read_csv("~/Desktop/MTA_Subway_Daily_Manhattan_Totals.csv")
daily_ridership_totals['date'] = pd.to_datetime(daily_ridership_totals['date'])
weekly_totals = daily_ridership_totals.set_index('date').resample('W-SUN')['ridership'].sum().reset_index()
weekly_totals.to_csv("MTA_Subway_Weekly_Manhattan_Totals.csv", index=False)

In [8]:
export_check = pd.read_csv("MTA_Subway_Weekly_Manhattan_Totals.csv")
export_check

          date  ridership
0   2023-01-01    1013185
1   2023-01-08   10290807
2   2023-01-15   11188333
3   2023-01-22   10738820
4   2023-01-29   11498691
5   2023-02-05   11294077
6   2023-02-12   12028749
7   2023-02-19   11983347
8   2023-02-26   10828114
9   2023-03-05   11806502
10  2023-03-12   12191080
11  2023-03-19   12544563
12  2023-03-26   12221586
13  2023-04-02   12378594
14  2023-04-09   12323223
15  2023-04-16   12121051
16  2023-04-23   12697578
17  2023-04-30   12846396
18  2023-05-07   13208511
19  2023-05-14   12885013
20  2023-05-21   13287128
21  2023-05-28   12649166
22  2023-06-04   11753017
23  2023-06-11   12452273
24  2023-06-18   12730000
25  2023-06-25   12414354
26  2023-07-02   12080489
27  2023-07-09   10265850
28  2023-07-16   12067118
29  2023-07-23   12415215
30  2023-07-30   12264669
31  2023-08-06   12035675
32  2023-08-13   11900551
33  2023-08-20   11566540
34  2023-08-27   11255370
35  2023-09-03   11536137
36  2023-09-10   11615867
37  2023-09-17   13184808
38  2023-09-24   13311727
39  2023-10-01   12179228
40  2023-10-08   13284633
41  2023-10-15   12786841
42  2023-10-22   13445783
43  2023-10-29   13778951
44  2023-11-05   13974020
45  2023-11-12   13365428
46  2023-11-19   13367321
47  2023-11-26   10554403
48  2023-12-03   13643795
49  2023-12-10   14221843
50  2023-12-17   14183886
51  2023-12-24   12454363
52  2023-12-31   10166404